const Movie = require('../models/Movie');

// @desc    Fetch all movies (Only fetching non-expired ones)
// @route   GET /api/movies
// @access  Public (Anyone can see movies)
exports.getMovies = async (req, res) => {
  try {
    // UPDATED: Only find movies where the expiration date is greater than or equal to RIGHT NOW
    const movies = await Movie.find({ expiresAt: { $gte: new Date() } });
    res.json(movies);
  } catch (error) {
    res.status(500).json({ message: 'Server Error' });
  }
};

// @desc    Add a new movie
// @route   POST /api/movies
// @access  Private/Admin Only
exports.createMovie = async (req, res) => {
  // UPDATED: Destructure the new showDate and showTime fields from the frontend
  const { title, genre, duration, status, showDate, showTime } = req.body;
  
  // req.file.path is the secure URL automatically generated by Cloudinary
  const posterUrl = req.file ? req.file.path : ''; 

  try {
    // UPDATED: Combine the date and time strings into a real Timestamp
    const expiresAt = new Date(`${showDate}T${showTime}`);

    const movie = new Movie({
      title, 
      genre, 
      duration, 
      posterUrl, 
      status,
      showDate,    // Save for frontend display
      showTime,    // Save for frontend display
      expiresAt,   // Save the hidden countdown clock
      addedBy: req.user._id
    });
    
    const createdMovie = await movie.save();
    res.status(201).json(createdMovie);
  } catch (error) {
    res.status(400).json({ message: 'Invalid movie data' });
  }
};

// @desc    Delete a movie
// @route   DELETE /api/movies/:id
// @access  Private/Admin Only
exports.deleteMovie = async (req, res) => {
  try {
    const movie = await Movie.findById(req.params.id);

    if (movie) {
      await movie.deleteOne();
      res.json({ message: 'Movie removed successfully' });
    } else {
      res.status(404).json({ message: 'Movie not found' });
    }
  } catch (error) {
    res.status(500).json({ message: 'Server Error' });
  }
};